### ISSUE TITLE
Possible to use in browser?

### ISSUE THREAD

**Issue by codetheweb** [winkjs/wink-eng-lite-model#4]
I realize this package is meant for Node.js, but I was wondering how hard it would be to use in the browser. The first error that I get when trying to bundle it is related to this package:

```
error - ./node_modules/wink-eng-lite-model/dist/load-ner-model.js:1:0
Module not found: Can't resolve 'fs'
```

It seems like it would be possible to rewrite that file to directly `require()` the JSON file instead of lazy loading it, but I'm guessing the lazy loading was done on purpose?

**Comment by prtksxna** [comment]
Hey @codetheweb 👋🏾 Thanks for raising this issue and sharing your approach. We’ve been trying to figure out a way to make this available for the browser too and ran into the same thing.

Hoping to work on this soon. Will keep you updated on this ticket.

**Comment by codetheweb** [comment]
Sounds good, thank you so much for the quick response.

**Comment by prtksxna** [comment]
Hello again, @codetheweb 👋🏽 You should be able to do this now by using the [wink-eng-lite-web-model](https://www.npmjs.com/package/wink-eng-lite-web-model). Do check out our new guide on [how to run winkNLP in the browser](https://winkjs.org/wink-nlp/how-to-run-wink-nlp-in-browser.html) and let us know how that went for you 😊

**Comment by codetheweb** [comment]
That's great to hear!

We actually decided to go with Electron instead for our app (and used the Node version of Wink) so I can't currently test this. But if we do need NLP in the browser in the future I'll be sure to check it out. 👍
